sudo: required

services: 
  - docker

before_install:
  - docker build -t sselvaganesh/docker-react-img -f Dockerfile.dev .

script:
  - docker run sselvaganesh/docker-react-img npm run test -- --coverage









